### ISSUE TITLE
dash充电电流疑问？

### ISSUE THREAD

**Issue by zhuqiang0320** [OnePlusOSS/android_kernel_oneplus_msm8998#11]
在OP-batterydata-3300mah.dtsi中，qcom,fastchg-current-ma = <3000>，但是dush标配充电器不是5V/4A的吗，这是不意味着到达电池只有3A？

**Comment by aviraxp** [comment]
https://github.com/OnePlusOSS/android_kernel_oneplus_msm8998/blob/ff86b46e27c8d5b5674c29b262b9d45769f89b39/drivers/power/supply/qcom/qpnp-smbcharger.c#L3576

首先从 charger device 读这个参数， 没有再从dts读。

**Comment by zhuqiang0320** [comment]
能给指出具体的代码吗？

**Comment by aviraxp** [comment]
我看错了，一加5充电不用这个驱动，那个参数没意义。

**Comment by aaronqiuchiu** [comment]
dash 快充电流是由mcu控制的，非AP跟PMIC控制，所以dtsi里面的配置不起作用！
