### ISSUE TITLE
Removal of 4.5.11 commit?

### ISSUE THREAD

**Issue by nathanchance** [OnePlusOSS/android_kernel_oneplus_msm8998#13]
I don't know if you guys even check GitHub issues anymore but this is worth a shot. Why was the 4.5.11 commit removed from source via a force push?

https://github.com/OnePlusOSS/android_kernel_oneplus_msm8998/commit/b9e9c1f3dec38dd874352c69bea269fcd60ca9f4

Was there an issue with it? Did you just want to repush with the same commit but with 4.5.12 in the commit message?

Force pushing a public tree like this is a git cardinal sin; it gives us custom kernel developers zero context as to why this commit was removed.  I ask two things from you for the future:

1. Please consider reverting commits in the future if there is an issue with them (noting what the issue is in the commit message).
2. Consider using a tagging system so that you can explicitly mark a commit as good for multiple OOS version (something like ```git tag -a "OOS-4.5.12" -m "Kernel source for OOS-4.5.12"```). This would help eliminate issues such as #8.

@aaronqiuchiu @leonfish77101 @Kevin-Shan

**Comment by nathanchance** [comment]
And now there's a new commit that has the exact same diff as the removed commit... What in the world is going on lol?

283f55b6d87e20ab69b820da0f89d53d3b97ef10

**Comment by aaronqiuchiu** [comment]
The code has been updated for 4.5.12
Thanks

**Comment by nathanchance** [comment]
@aaronqiuchiu the response is much appreciated!
