### ISSUE TITLE
Sourcecode is not updated

### ISSUE THREAD

**Issue by Alucard24** [OnePlusOSS/android_kernel_oneplus_msm8998#18]
Please push the updated and working code. Sourcecode is not good and it causes kernel panic and reboot once it is compiled and flashed....
Also CONFIG_OEM_FORCE_DUMP sourcecode is missing!

**Comment by aaronqiuchiu** [comment]
https://github.com/OnePlusOSS/android_kernel_oneplus_msm8998/commits/oneplus/QC8998_Q_10.0
