### ISSUE TITLE
git clone https url , show warning: remote HEAD refers to nonexistent ref, unable to checkout.

### ISSUE THREAD

**Issue by HHPLow** [OnePlusOSS/android_kernel_oneplus_msm8998#2]
You need use 
`$git branch -a`
show all remote branch， and you can see
`remotes/origin/oneplus/QC8998_N_7.1`
then 
`$git checkout remotes/origin/oneplus/QC8998_N_7.1 -b NameYouWant `
now you can see  the code.
Maybe it's very easy to find the answer. XD.
Find from [stackoverflow](https://stackoverflow.com/questions/11893678/warning-remote-head-refers-to-nonexistent-ref-unable-to-checkout)

**Comment by aaronqiuchiu** [comment]
@xiaodiandi what can i help you ?

**Comment by HHPLow** [comment]
@aaronqiuchiu  
I git clone the code done, git notice me that error
`remote HEAD refers to nonexistent ref, unable to checkout`, and use `ls -l` only can see the .git and no code .So I find this solution to checkout the code.

Usually when I `git clone` the git done from github , the code will show in dir. but this not show in dir, must 
manual use `$git checkout remotes/origin/oneplus/QC8998_N_7.1 -b NameYouWant` to checkouot the code.

Is there something wrong?
Thanks.

**Comment by aaronqiuchiu** [comment]
@XiaoDianDi we have fix this issue, please try again
git clone https://github.com/OnePlusOSS/android_kernel_oneplus_msm8998.git

Thanks

**Comment by darshan1205** [comment]
@aaronqiuchiu can't find any update though :\

**Comment by aaronqiuchiu** [comment]
@darshan1205 could you try 
git clone https://github.com/OnePlusOSS/android_kernel_oneplus_msm8998.git
this again and still have problem ?

**Comment by HHPLow** [comment]
@aaronqiuchiu 

```shell
$ git clone https://github.com/OnePlusOSS/android_kernel_oneplus_msm8998.git
Cloning into 'android_kernel_oneplus_msm8998'...
remote: Counting objects: 4652724, done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 4652724 (delta 0), reused 0 (delta 0), pack-reused 4652721
Receiving objects: 100% (4652724/4652724), 840.58 MiB | 904 KiB/s, done.
Resolving deltas: 100% (3906782/3906782), done.

$ ls
android_kernel_oneplus_msm8998

$ git branch -a
* oneplus/QC8998_N_7.1
  remotes/origin/HEAD -> origin/oneplus/QC8998_N_7.1
  remotes/origin/oneplus/QC8998_N_7.1

```
Fixed, thanks.

**Comment by aaronqiuchiu** [comment]
^_^
