### ISSUE TITLE
Android 10 Kernel

### ISSUE THREAD

**Issue by neobuddy89** [OnePlusOSS/android_kernel_oneplus_msm8998#22]
New Open Beta - Android 10 is available yet kernel source is not released.

**Comment by lyq1996** [comment]
@aaronqiuchiu  
Please open source, thank you.

**Comment by neobuddy89** [comment]
@aaronqiuchiu
Beta 2 released. No kernel source?

**Comment by jgcaap** [comment]
Hey guys. Share the kernel we are auxious to play with it! Thanks.

**Comment by Janres** [comment]
Kernel source please. Thank you!

**Comment by aaronqiuchiu** [comment]
Sorry for the late response, Beta version kernel sourcecode released now
https://github.com/OnePlusOSS/android_kernel_oneplus_msm8998/commits/oneplus/QC8998_Q_10.0_Beta
