### ISSUE TITLE
Source code not updated

### ISSUE THREAD

**Issue by jgcaap** [OnePlusOSS/android_kernel_oneplus_msm8998#23]
Beta 3 was released and source code of kernel is not updated yet. Could you please update it? Thanks.

**Comment by jgcaap** [comment]
Official Rom is out and no source code updated.

**Comment by bluhaidah** [comment]
Please release the new source code.
Thanks

**Comment by neobuddy89** [comment]
Hi,
Can you please update with stable source code?

**Comment by Cris--** [comment]
Please release the kernel Q stable source code for our beloved OnePlus 5T for the/your community. Thanks!

**Comment by Pokemetti** [comment]
Please keep at least the kernel source open and update this repo. Thanks

**Comment by isirisi** [comment]
Please let us stay up to date with the stable source code. Thank you!

**Comment by shivanshvermak** [comment]
Please consider updating kernel source code. Thanks.

**Comment by ychoon94** [comment]
Please update kernel source

**Comment by kroxkr** [comment]
Hey please update this repo with the latest kernel source.
thanks!

**Comment by sunilpaulmathew** [comment]
Extremely sad to see OnePlus started violating GPL.

**Comment by KaZo58** [comment]
Is anyone going to sue/report OnePlus?

**Comment by madsunable** [comment]
Please update your kernel source. It's so annoying...

**Comment by jgcaap** [comment]
Oneplus please update the source when possible. Eager to play with it. Many thanks

**Comment by archz2** [comment]
Dear OnePlus team, Please update your kernel source. It's been quite a while since Android Q came out for OnePlus 5T

**Comment by Janres** [comment]
Please release kernel source stable Android 10. Thanks

**Comment by Janres** [comment]
@aaronqiuchiu

**Comment by DaFlowah** [comment]
@aaronqiuchiu any update on this?

**Comment by aaronqiuchiu** [comment]
https://github.com/OnePlusOSS/android_kernel_oneplus_msm8998/commits/oneplus/QC8998_Q_10.0

**Comment by Pokemetti** [comment]
Finally, geez, if there is nothing to hide releasing source shouldn't take too long, right?
