### ISSUE TITLE
Compile fatal error

### ISSUE THREAD

**Issue by rancidfrog** [OnePlusOSS/android_kernel_oneplus_msm8998#3]
```
drivers/bluetooth/btfm_slim.c:26:23: fatal error: btfm_slim.h: No such file or directory
 #include <btfm_slim.h>
                       ^
compilation terminated.

sound/soc/msm/msm8998.c:36:26: fatal error: device_event.h: No such file or directory
 #include <device_event.h>
                          ^
compilation terminated.

```
And later if you change <> to ""
```
drivers/bluetooth/btfm_slim.c:27:31: fatal error: btfm_slim_wcn3990.h: No such file or directory
 #include <btfm_slim_wcn3990.h>
                               ^
compilation terminated.

In file included from drivers/bluetooth/btfm_slim.c:27:0:
drivers/bluetooth/btfm_slim_wcn3990.h:15:23: fatal error: btfm_slim.h: No such file or directory
 #include <btfm_slim.h>
                       ^
compilation terminated.

drivers/bluetooth/btfm_slim_codec.c:27:23: fatal error: btfm_slim.h: No such file or directory
 #include <btfm_slim.h>
                       ^
compilation terminated.
```

**Comment by aaronqiuchiu** [comment]
@rancidfrog please help check your local source code again, i check github code again all your build error logs show file included. 
https://github.com/OnePlusOSS/android_kernel_oneplus_msm8998/blob/oneplus/QC8998_N_7.1/drivers/bluetooth/btfm_slim.h
https://github.com/OnePlusOSS/android_kernel_oneplus_msm8998/blob/oneplus/QC8998_N_7.1/drivers/bluetooth/btfm_slim_wcn3990.h
https://github.com/OnePlusOSS/android_kernel_oneplus_msm8998/blob/oneplus/QC8998_N_7.1/sound/soc/msm/device_event.h

Thanks

**Comment by rancidfrog** [comment]
Yes, I know.
I think it should be:
```
#include "btfm_slim.h"
```
Instead of,
```
#include <btfm_slim.h>                                            
```
Currently, it does not compile with <>, changing to "", continues compilation but more errors.

Somebody got it to compile but a lot of fixes: https://github.com/adinkwok/oneplus5-kernel/commit/ec4ec687ba23609b9c323145c7d509262b0f025f

Current Source code not compiling for me.
You can try to compile,  it gives errors like first post.

@aaronqiuchiu 
- **What magic are you doing for it to compile?**
- Repo has wrong/broken code?

**Comment by aaronqiuchiu** [comment]
@rancidfrog i have try it and compile success, i have no idea about this compile fail. relate config of build server ?

make[1]: Entering directory '/home/qiuchangping/workplus/16859-MR1-devicetree/MSM8998/android/out/target/product/msm8998/obj/kernel/msm-4.4'
  INSTALL block/test-iosched.ko
  INSTALL drivers/char/rdbg.ko
  INSTALL drivers/media/platform/msm/broadcast/tspp.ko
  INSTALL drivers/media/platform/msm/dvb/adapter/mpq-adapter.ko
  INSTALL drivers/net/wireless/ath/wil6210/wil6210.ko
  INSTALL drivers/media/platform/msm/dvb/demux/mpq-dmx-hw-plugin.ko
  INSTALL drivers/scsi/ufs/ufs_test.ko
  INSTALL net/bridge/br_netfilter.ko
  DEPMOD  4.4.21+
make[1]: Leaving directory '/home/qiuchangping/workplus/16859-MR1-devicetree/MSM8998/android/out/target/product/msm8998/obj/kernel/msm-4.4'
make: Leaving directory '/home/qiuchangping/workplus/16859-MR1-devicetree/MSM8998/android/kernel/msm-4.4'
[100% 5/5] Target boot image: out/target/product/msm8998/boot.img
out/target/product/msm8998/boot.img maxsize=68395008 blocksize=135168 total=19506472 reserve=811008

#### make completed successfully (05:07 (mm:ss)) ####

**Comment by MasterDomino** [comment]
same issue here cannot compile with same errors on
```sound/soc/msm/msm8998.c:36:26: fatal error: device_event.h: No such file or directory
 #include <device_event.h>
                          ^
compilation terminated.
scripts/Makefile.build:258: recipe for target 'sound/soc/msm/msm8998.o' failed
make[3]: *** [sound/soc/msm/msm8998.o] Error 1
scripts/Makefile.build:403: recipe for target 'sound/soc/msm' failed
make[2]: *** [sound/soc/msm] Error 2
scripts/Makefile.build:403: recipe for target 'sound/soc' failed
make[1]: *** [sound/soc] Error 2
Makefile:960: recipe for target 'sound' failed
make: *** [sound] Error 2
```
and same with btfm like @rancidfrog also using aarch64-linux-android-4.9-uber toolchains i dont really know whats the cause.
[log.txt](https://github.com/OnePlusOSS/android_kernel_oneplus_msm8998/files/1132441/log.txt)

**Comment by pagaiba** [comment]
@aaronqiuchiu what toolchain, system and defconfig are you using to compile it if I may ask?

**Comment by mikroskeem** [comment]
FYI you need to build CAF and related kernels with `make O=outdir`, otherwise you're going to end up with weird errors like these.

**Comment by figforg** [comment]
Where did you change <> to "" ?
