### ISSUE TITLE
 Respect the GNU GPLv2!!

### ISSUE THREAD

**Issue by ghost** [OnePlusOSS/android_kernel_oneplus_msm8998#8]
Linux is distributed under the GNU GPLv2 license, you can not distribute software without source!
Oneplus have just violated the GNU GPLv2 with the distribution of Oxygen 4.5.6 and Oxygen 4.5.7!
I will contact the copyright owner (Linus Torvalds) to report the repeated violation of the license by Oneplus

Thanks for the attention
Ernesto Castellotti
Italy

**Comment by MasterDomino** [comment]
get some help

**Comment by Orion116** [comment]
https://github.com/OnePlusOSS/android_kernel_oneplus_msm8998/commit/ce3b536e35278f2971627c51fd5b263ab6b5b934

**Comment by ghost** [comment]
Oh good! However shameful for the lack of upgrade to the source from 4.5.5 .

**Comment by MasterDomino** [comment]
4.5.5 was before this one and i guess changes from 4.5.6 are included in current iteration, soo stop spazing geez...
